'use client';

import { useState, useMemo, useEffect } from 'react';
import { format } from 'date-fns';
import { motion } from 'framer-motion';
import {
  Briefcase,
  Plus,
  Search,
  Trash2,
  Eye,
  Play,
  FileText,
  MapPin,
  Clock,
  DollarSign,
  CalendarDays,
  StickyNote,
  Sparkles,
  Send,
  Loader2,
} from 'lucide-react';
import { CalendarIcon } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Card } from '@/components/ui/card';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Skeleton } from '@/components/ui/skeleton';
import { Separator } from '@/components/ui/separator';
import PaginationControls from '@/components/ui/pagination-controls';
import ConfirmModal from '@/components/ConfirmModal';
import { mockJobs, mockClients, type Job } from '@/lib/mock-data';
import { toast } from '@/components/ui/sonner';
import { paginateArray } from '@/lib/pagination';

const ITEMS_PER_PAGE = 8;

const statusColor = (s: Job['status']) => {
  switch (s) {
    case 'pending':
      return 'bg-yellow-500/10 text-yellow-600 dark:text-yellow-400 border-yellow-500/20';
    case 'in_progress':
      return 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20';
    case 'completed':
      return 'bg-green-500/10 text-green-600 dark:text-green-400 border-green-500/20';
  }
};

const statusLabel = (s: Job['status']) => {
  switch (s) {
    case 'pending':
      return 'Pending';
    case 'in_progress':
      return 'In Progress';
    case 'completed':
      return 'Completed';
  }
};

interface ExtendedJob extends Job {
  price?: number;
  time?: string;
  location?: string;
  notes?: string;
  contract?: string;
  contractSent?: boolean;
}

const generateMockContract = (job: ExtendedJob, clientName: string): string => {
  return `SERVICE AGREEMENT CONTRACT

Contract Number: SC-${Date.now().toString().slice(-6)}
Date: ${format(new Date(), 'MMMM d, yyyy')}

PARTIES:
This Service Agreement ("Agreement") is entered into between:
- Service Provider: Servix OS Business ("Provider")
- Client: ${clientName} ("Client")

SCOPE OF WORK:
Service: ${job.title}
Description: ${job.notes || 'Standard service as agreed upon by both parties.'}

SCHEDULE:
- Start Date: ${job.date}
- Scheduled Time: ${job.time || 'To be confirmed'}
- Location: ${job.location || "Client's premises"}

COMPENSATION:
- Total Price: $${(job.price ?? 0).toLocaleString()}
- Payment Terms: Due upon completion of services
- Payment Method: Cash, check, or electronic transfer

TERMS AND CONDITIONS:
1. The Provider agrees to perform the services described above in a professional and workmanlike manner.
2. The Client agrees to provide reasonable access to the work area and any necessary utilities.
3. Any changes to the scope of work must be agreed upon in writing by both parties.
4. Either party may cancel this agreement with 24-hour notice.
5. The Provider carries appropriate insurance for all work performed.

SIGNATURES:
Provider: _________________________ Date: _________
Client: _________________________ Date: _________

This contract is generated by Servix OS and is legally binding upon signature by both parties.`;
};

const Jobs = () => {
  const [loading, setLoading] = useState(true);
  const [jobs, setJobs] = useState<ExtendedJob[]>([]);
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [clientFilter, setClientFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState('all');
  const [createOpen, setCreateOpen] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<ExtendedJob | null>(null);
  const [viewJob, setViewJob] = useState<ExtendedJob | null>(null);
  const [selectedJobIds, setSelectedJobIds] = useState<string[]>([]);
  const [bulkDeleteOpen, setBulkDeleteOpen] = useState(false);
  const [bulkStatus, setBulkStatus] = useState<Job['status']>('pending');

  // Contract states
  const [contractGenerating, setContractGenerating] = useState(false);
  const [contractReviewOpen, setContractReviewOpen] = useState(false);
  const [contractText, setContractText] = useState('');

  // Create form state
  const [formTitle, setFormTitle] = useState('');
  const [formClientId, setFormClientId] = useState('');
  const [formDate, setFormDate] = useState<Date>(new Date());
  const [formPrice, setFormPrice] = useState('');
  const [formLocation, setFormLocation] = useState('');
  const [formNotes, setFormNotes] = useState('');

  useEffect(() => {
    const t = setTimeout(() => {
      const extended: ExtendedJob[] = mockJobs.map((j) => ({
        ...j,
        price: Math.floor(Math.random() * 5000) + 500,
        time: '09:00 AM',
        location: mockClients.find((c) => c.id === j.clientId)?.jobLocation ?? '',
        notes: '',
      }));
      setJobs(extended);
      setLoading(false);
    }, 800);
    return () => clearTimeout(t);
  }, []);

  const filtered = useMemo(() => {
    const q = search.toLowerCase();
    return jobs.filter((job) => {
      const client = mockClients.find((c) => c.id === job.clientId);
      const matchSearch =
        job.title.toLowerCase().includes(q) || client?.fullName.toLowerCase().includes(q);
      const matchClient = clientFilter === 'all' || job.clientId === clientFilter;
      const matchStatus = statusFilter === 'all' || job.status === statusFilter;
      return matchSearch && matchClient && matchStatus;
    });
  }, [jobs, search, clientFilter, statusFilter]);

  const pagination = useMemo(
    () => paginateArray(filtered, page, ITEMS_PER_PAGE),
    [filtered, page]
  );
  const { data: paginated, meta: paginationMeta } = pagination;

  useEffect(() => {
    if (page !== paginationMeta.page) {
      setPage(paginationMeta.page);
    }
  }, [page, paginationMeta.page]);

  const handleDelete = () => {
    if (!deleteTarget) return;
    setJobs((prev) => prev.filter((j) => j.id !== deleteTarget.id));
    setSelectedJobIds((prev) => prev.filter((id) => id !== deleteTarget.id));
    toast.success('Job deleted', { description: `"${deleteTarget.title}" has been removed.` });
    setDeleteTarget(null);
  };

  const resetForm = () => {
    setFormTitle('');
    setFormClientId('');
    setFormDate(new Date());
    setFormPrice('');
    setFormLocation('');
    setFormNotes('');
  };

  const handleCreate = () => {
    if (!formTitle.trim() || !formClientId) {
      toast.error('Validation Error', { description: 'Title and client are required.' });
      return;
    }
    const newJob: ExtendedJob = {
      id: `j-${Date.now()}`,
      clientId: formClientId,
      title: formTitle,
      date: format(formDate, 'yyyy-MM-dd'),
      status: 'pending',
      price: Number(formPrice) || 0,
      location: formLocation,
      notes: formNotes,
    };
    setJobs((prev) => [newJob, ...prev]);
    toast.success('Job created', { description: `"${newJob.title}" added successfully.` });
    setCreateOpen(false);
    resetForm();
  };

  const selectedJobsCount = selectedJobIds.length;
  const allVisibleSelected =
    paginated.length > 0 && paginated.every((job) => selectedJobIds.includes(job.id));
  const someVisibleSelected =
    paginated.some((job) => selectedJobIds.includes(job.id)) && !allVisibleSelected;

  const handleToggleJobSelection = (jobId: string, checked: boolean) => {
    setSelectedJobIds((prev) => {
      if (checked) {
        if (prev.includes(jobId)) return prev;
        return [...prev, jobId];
      }
      return prev.filter((id) => id !== jobId);
    });
  };

  const handleToggleVisibleSelection = (checked: boolean) => {
    if (!paginated.length) return;
    const visibleIds = paginated.map((job) => job.id);
    setSelectedJobIds((prev) => {
      if (checked) {
        return Array.from(new Set([...prev, ...visibleIds]));
      }
      return prev.filter((id) => !visibleIds.includes(id));
    });
  };

  const handleBulkStatusUpdate = () => {
    if (!selectedJobsCount) return;
    const selectedIds = new Set(selectedJobIds);
    setJobs((prev) =>
      prev.map((job) => (selectedIds.has(job.id) ? { ...job, status: bulkStatus } : job))
    );
    setViewJob((prev) => (prev && selectedIds.has(prev.id) ? { ...prev, status: bulkStatus } : prev));
    toast.success('Jobs updated', {
      description: `${selectedJobsCount} job${selectedJobsCount > 1 ? 's' : ''} marked as ${statusLabel(bulkStatus)}.`,
    });
    setSelectedJobIds([]);
  };

  const handleBulkDelete = () => {
    if (!selectedJobsCount) return;
    const selectedIds = new Set(selectedJobIds);
    setJobs((prev) => prev.filter((job) => !selectedIds.has(job.id)));
    setViewJob((prev) => (prev && selectedIds.has(prev.id) ? null : prev));
    toast.success('Jobs deleted', {
      description: `${selectedJobsCount} job${selectedJobsCount > 1 ? 's have' : ' has'} been removed.`,
    });
    setSelectedJobIds([]);
    setBulkDeleteOpen(false);
  };

  useEffect(() => {
    setSelectedJobIds((prev) => {
      if (!prev.length) return prev;
      const existingIds = new Set(jobs.map((job) => job.id));
      return prev.filter((id) => existingIds.has(id));
    });
  }, [jobs]);

  const handleStartJob = (job: ExtendedJob) => {
    setJobs((prev) =>
      prev.map((j) => (j.id === job.id ? { ...j, status: 'in_progress' as const } : j))
    );
    setViewJob((prev) => (prev && prev.id === job.id ? { ...prev, status: 'in_progress' } : prev));
    toast.success('Job started', { description: `"${job.title}" is now in progress.` });
  };

  const handleCreateInvoice = (job: ExtendedJob) => {
    toast.success('Invoice created', { description: `Invoice generated for "${job.title}".` });
  };

  const handleGenerateContract = async () => {
    if (!viewJob) return;
    setContractGenerating(true);
    // Simulate AI contract generation
    await new Promise((r) => setTimeout(r, 2500));
    const client = mockClients.find((c) => c.id === viewJob.clientId);
    const contract = generateMockContract(viewJob, client?.fullName ?? 'Unknown Client');
    setContractText(contract);
    setContractGenerating(false);
    setContractReviewOpen(true);
  };

  const handleSendContract = () => {
    if (!viewJob) return;
    setJobs((prev) =>
      prev.map((j) =>
        j.id === viewJob.id ? { ...j, contract: contractText, contractSent: true } : j
      )
    );
    setViewJob((prev) => (prev ? { ...prev, contract: contractText, contractSent: true } : prev));
    setContractReviewOpen(false);
    toast.success('Contract sent', {
      description: `Contract has been sent to the client for review and signature.`,
    });
  };

  return (
    <div className='space-y-4 sm:space-y-6'>
      {/* Header */}
      <div className='flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between'>
        <div>
          <h1 className='text-xl font-bold tracking-tight sm:text-2xl'>Jobs</h1>
          <p className='text-sm text-muted-foreground'>Manage and track all jobs</p>
        </div>
        <Button onClick={() => setCreateOpen(true)} className='w-full gap-2 sm:w-auto'>
          <Plus size={16} /> New Job
        </Button>
      </div>

      {/* Filters */}
      <div className='flex flex-col gap-3 sm:flex-row sm:items-center'>
        <div className='relative w-full flex-1 sm:max-w-sm'>
          <Search className='absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground' />
          <Input
            placeholder='Search jobs...'
            value={search}
            onChange={(e) => {
              setSearch(e.target.value);
              setPage(1);
            }}
            className='pl-9'
          />
        </div>
        <Select
          value={clientFilter}
          onValueChange={(v) => {
            setClientFilter(v);
            setPage(1);
          }}
        >
          <SelectTrigger className='w-full sm:w-[180px]'>
            <SelectValue placeholder='All Clients' />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value='all'>All Clients</SelectItem>
            {mockClients.map((c) => (
              <SelectItem key={c.id} value={c.id}>
                {c.fullName}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select
          value={statusFilter}
          onValueChange={(v) => {
            setStatusFilter(v);
            setPage(1);
          }}
        >
          <SelectTrigger className='w-full sm:w-[160px]'>
            <SelectValue placeholder='All Statuses' />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value='all'>All Statuses</SelectItem>
            <SelectItem value='pending'>Pending</SelectItem>
            <SelectItem value='in_progress'>In Progress</SelectItem>
            <SelectItem value='completed'>Completed</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {selectedJobsCount > 0 && (
        <Card className='card-shadow p-3'>
          <div className='flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between'>
            <p className='text-sm font-medium'>
              {selectedJobsCount} job{selectedJobsCount > 1 ? 's' : ''} selected
            </p>
            <div className='flex flex-col gap-2 sm:flex-row sm:items-center'>
              <Select
                value={bulkStatus}
                onValueChange={(value: Job['status']) => setBulkStatus(value)}
              >
                <SelectTrigger className='w-full sm:w-[180px]'>
                  <SelectValue placeholder='Set status' />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value='pending'>Pending</SelectItem>
                  <SelectItem value='in_progress'>In Progress</SelectItem>
                  <SelectItem value='completed'>Completed</SelectItem>
                </SelectContent>
              </Select>
              <Button variant='outline' onClick={handleBulkStatusUpdate}>
                Update Status
              </Button>
              <Button variant='destructive' onClick={() => setBulkDeleteOpen(true)}>
                Delete Selected
              </Button>
            </div>
          </div>
        </Card>
      )}

      {/* Table */}
      {loading ? (
        <div className='space-y-3'>
          {Array.from({ length: 5 }).map((_, i) => (
            <Skeleton key={i} className='h-12 rounded-lg' />
          ))}
        </div>
      ) : (
        <>
          <div className='space-y-3 md:hidden'>
            {paginated.length === 0 ? (
              <Card className='card-shadow p-6 text-center text-sm text-muted-foreground'>
                <Briefcase className='mx-auto mb-2 h-8 w-8 opacity-40' />
                No jobs found.
              </Card>
            ) : (
              paginated.map((job, i) => {
                const client = mockClients.find((c) => c.id === job.clientId);
                return (
                  <motion.div
                    key={job.id}
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: i * 0.03 }}
                  >
                    <Card className='card-shadow p-3'>
                      <div className='space-y-2'>
                        <div className='flex items-start justify-between gap-2'>
                          <div className='flex items-start gap-2'>
                            <Checkbox
                              checked={selectedJobIds.includes(job.id)}
                              onCheckedChange={(checked) =>
                                handleToggleJobSelection(job.id, checked === true)
                              }
                              aria-label={`Select ${job.title}`}
                            />
                            <p className='text-sm font-medium leading-tight'>{job.title}</p>
                          </div>
                          <Badge variant='outline' className={statusColor(job.status)}>
                            {statusLabel(job.status)}
                          </Badge>
                        </div>
                        <p className='text-xs text-muted-foreground'>{client?.fullName ?? 'Unknown'}</p>
                        <p className='text-xs text-muted-foreground'>{job.date}</p>
                        <div className='flex justify-end gap-1 pt-1'>
                          <Button variant='ghost' size='icon' onClick={() => setViewJob(job)}>
                            <Eye size={16} />
                          </Button>
                          <Button
                            variant='ghost'
                            size='icon'
                            onClick={() => setDeleteTarget(job)}
                            className='text-destructive hover:text-destructive'
                          >
                            <Trash2 size={16} />
                          </Button>
                        </div>
                      </div>
                    </Card>
                  </motion.div>
                );
              })
            )}
          </div>

          <Card className='card-shadow hidden overflow-hidden md:block'>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className='w-10'>
                    <Checkbox
                      checked={allVisibleSelected ? true : someVisibleSelected ? 'indeterminate' : false}
                      onCheckedChange={(checked) => handleToggleVisibleSelection(checked === true)}
                      aria-label='Select visible jobs'
                    />
                  </TableHead>
                  <TableHead>Job Title</TableHead>
                  <TableHead>Client</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className='text-right'>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {paginated.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={6} className='py-10 text-center text-muted-foreground'>
                      <Briefcase className='mx-auto mb-2 h-8 w-8 opacity-40' /> No jobs found.
                    </TableCell>
                  </TableRow>
                ) : (
                  paginated.map((job, i) => {
                    const client = mockClients.find((c) => c.id === job.clientId);
                    return (
                      <motion.tr
                        key={job.id}
                        initial={{ opacity: 0, y: 8 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: i * 0.03 }}
                        className='border-b transition-colors hover:bg-muted/50'
                      >
                        <TableCell>
                          <Checkbox
                            checked={selectedJobIds.includes(job.id)}
                            onCheckedChange={(checked) =>
                              handleToggleJobSelection(job.id, checked === true)
                            }
                            aria-label={`Select ${job.title}`}
                          />
                        </TableCell>
                        <TableCell className='font-medium'>{job.title}</TableCell>
                        <TableCell>{client?.fullName ?? 'Unknown'}</TableCell>
                        <TableCell>{job.date}</TableCell>
                        <TableCell>
                          <Badge variant='outline' className={statusColor(job.status)}>
                            {statusLabel(job.status)}
                          </Badge>
                        </TableCell>
                        <TableCell className='text-right'>
                          <div className='flex justify-end gap-1'>
                            <Button variant='ghost' size='icon' onClick={() => setViewJob(job)}>
                              <Eye size={16} />
                            </Button>
                            <Button
                              variant='ghost'
                              size='icon'
                              onClick={() => setDeleteTarget(job)}
                              className='text-destructive hover:text-destructive'
                            >
                              <Trash2 size={16} />
                            </Button>
                          </div>
                        </TableCell>
                      </motion.tr>
                    );
                  })
                )}
              </TableBody>
            </Table>
          </Card>
          <PaginationControls
            meta={paginationMeta}
            onPageChange={setPage}
            className='flex items-center justify-between gap-2 border-t px-1 py-3 sm:px-2 md:rounded-b-lg md:border md:px-4'
            controlsClassName='flex gap-1'
          />
        </>
      )}

      {/* Delete modal */}
      <ConfirmModal
        open={!!deleteTarget}
        onOpenChange={(open) => {
          if (!open) setDeleteTarget(null);
        }}
        title='Delete Job'
        description={`Are you sure you want to delete "${deleteTarget?.title}"? This action cannot be undone.`}
        confirmLabel='Delete'
        onConfirm={handleDelete}
        variant='destructive'
      />

      <ConfirmModal
        open={bulkDeleteOpen}
        onOpenChange={setBulkDeleteOpen}
        title='Delete Selected Jobs'
        description={`Are you sure you want to delete ${selectedJobsCount} selected job${selectedJobsCount > 1 ? 's' : ''}? This action cannot be undone.`}
        confirmLabel='Delete Selected'
        onConfirm={handleBulkDelete}
        variant='destructive'
      />

      {/* View Job Detail Dialog */}
      <Dialog
        open={!!viewJob}
        onOpenChange={(open) => {
          if (!open) setViewJob(null);
        }}
      >
        <DialogContent className='max-h-[90dvh] overflow-y-auto sm:max-w-lg'>
          <DialogHeader>
            <DialogTitle>Job Details</DialogTitle>
            <DialogDescription>View job information and take actions</DialogDescription>
          </DialogHeader>
          {viewJob &&
            (() => {
              const client = mockClients.find((c) => c.id === viewJob.clientId);
              return (
                <div className='space-y-4 py-2'>
                  <div className='flex items-center justify-between'>
                    <h3 className='text-lg font-semibold'>{viewJob.title}</h3>
                    <Badge variant='outline' className={statusColor(viewJob.status)}>
                      {statusLabel(viewJob.status)}
                    </Badge>
                  </div>
                  <Separator />
                  <div className='grid gap-3 sm:grid-cols-2'>
                    <div className='flex items-center gap-2 text-sm'>
                      <Briefcase size={14} className='text-muted-foreground' />
                      <span className='text-muted-foreground'>Client:</span>
                      <span className='font-medium'>{client?.fullName ?? 'Unknown'}</span>
                    </div>
                    <div className='flex items-center gap-2 text-sm'>
                      <CalendarDays size={14} className='text-muted-foreground' />
                      <span className='text-muted-foreground'>Date:</span>
                      <span className='font-medium'>{viewJob.date}</span>
                    </div>
                    <div className='flex items-center gap-2 text-sm'>
                      <DollarSign size={14} className='text-muted-foreground' />
                      <span className='text-muted-foreground'>Price:</span>
                      <span className='font-medium'>${(viewJob.price ?? 0).toLocaleString()}</span>
                    </div>
                    <div className='flex items-center gap-2 text-sm'>
                      <Clock size={14} className='text-muted-foreground' />
                      <span className='text-muted-foreground'>Time:</span>
                      <span className='font-medium'>{viewJob.time || 'N/A'}</span>
                    </div>
                    <div className='flex items-center gap-2 text-sm sm:col-span-2'>
                      <MapPin size={14} className='text-muted-foreground' />
                      <span className='text-muted-foreground'>Location:</span>
                      <span className='font-medium'>{viewJob.location || 'N/A'}</span>
                    </div>
                  </div>
                  {viewJob.notes && (
                    <>
                      <Separator />
                      <div className='space-y-1'>
                        <div className='flex items-center gap-2 text-sm text-muted-foreground'>
                          <StickyNote size={14} /> Notes
                        </div>
                        <p className='text-sm'>{viewJob.notes}</p>
                      </div>
                    </>
                  )}
                  <Separator />
                  <div className='flex flex-wrap gap-2'>
                    {viewJob.status === 'pending' && (
                      <Button onClick={() => handleStartJob(viewJob)} className='gap-2'>
                        <Play size={14} /> Start Job
                      </Button>
                    )}
                    {viewJob.status === 'completed' && (
                      <Button
                        onClick={() => handleCreateInvoice(viewJob)}
                        variant='outline'
                        className='gap-2'
                      >
                        <FileText size={14} /> Create Invoice
                      </Button>
                    )}
                    {viewJob.status === 'in_progress' && (
                      <>
                        <Button
                          onClick={() => {
                            setJobs((prev) =>
                              prev.map((j) =>
                                j.id === viewJob.id ? { ...j, status: 'completed' as const } : j
                              )
                            );
                            setViewJob((prev) => (prev ? { ...prev, status: 'completed' } : prev));
                            toast.success('Job completed', {
                              description: `"${viewJob.title}" marked as completed.`,
                            });
                          }}
                          className='gap-2'
                        >
                          <Briefcase size={14} /> Mark Complete
                        </Button>
                        <Button
                          onClick={() => handleCreateInvoice(viewJob)}
                          variant='outline'
                          className='gap-2'
                        >
                          <FileText size={14} /> Create Invoice
                        </Button>
                      </>
                    )}
                    {/* Generate / Send Contract Button */}
                    {!viewJob.contractSent ? (
                      <Button
                        onClick={
                          viewJob.contract
                            ? () => {
                                setContractText(viewJob.contract!);
                                setContractReviewOpen(true);
                              }
                            : handleGenerateContract
                        }
                        variant='outline'
                        className='gap-2'
                        disabled={contractGenerating}
                      >
                        {contractGenerating ? (
                          <>
                            <Loader2 size={14} className='animate-spin' /> Generating...
                          </>
                        ) : viewJob.contract ? (
                          <>
                            <Send size={14} /> Send Contract
                          </>
                        ) : (
                          <>
                            <Sparkles size={14} /> Generate Contract
                          </>
                        )}
                      </Button>
                    ) : (
                      <Badge
                        variant='outline'
                        className='bg-emerald-500/10 text-emerald-600 border-emerald-500/20 gap-1.5 py-1.5 px-3'
                      >
                        <FileText size={14} /> Contract Sent
                      </Badge>
                    )}
                  </div>
                </div>
              );
            })()}
        </DialogContent>
      </Dialog>

      {/* Contract Review Dialog - Non-closable */}
      <Dialog
        open={contractReviewOpen}
        onOpenChange={() => {
          /* non-closable */
        }}
      >
        <DialogContent
          className='flex max-h-[90dvh] flex-col sm:max-w-2xl'
          onPointerDownOutside={(e) => e.preventDefault()}
          onEscapeKeyDown={(e) => e.preventDefault()}
        >
          <DialogHeader>
            <DialogTitle className='flex items-center gap-2'>
              <FileText size={18} className='text-primary' /> Contract Review
            </DialogTitle>
            <DialogDescription>
              Review and edit the AI-generated contract before sending it to the client.
            </DialogDescription>
          </DialogHeader>
          <div className='flex-1 min-h-0 overflow-hidden'>
            <Textarea
              value={contractText}
              onChange={(e) => setContractText(e.target.value)}
              className='h-full min-h-[300px] max-h-[50vh] font-mono text-xs resize-none'
            />
          </div>
          <DialogFooter>
            <Button
              variant='outline'
              onClick={() => {
                setContractReviewOpen(false);
              }}
            >
              Save Draft
            </Button>
            <Button onClick={handleSendContract} className='gap-2'>
              <Send size={14} /> Send Contract
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Create Job Dialog */}
      <Dialog
        open={createOpen}
        onOpenChange={(open) => {
          setCreateOpen(open);
          if (!open) resetForm();
        }}
      >
        <DialogContent className='max-h-[90dvh] overflow-y-auto sm:max-w-lg'>
          <DialogHeader>
            <DialogTitle>Create New Job</DialogTitle>
            <DialogDescription>Fill in the details to create a new job</DialogDescription>
          </DialogHeader>
          <div className='space-y-4 py-2'>
            <div className='space-y-1.5'>
              <Label>Title</Label>
              <Input
                placeholder='Job title'
                value={formTitle}
                onChange={(e) => setFormTitle(e.target.value)}
              />
            </div>
            <div className='space-y-1.5'>
              <Label>Client</Label>
              <Select value={formClientId} onValueChange={setFormClientId}>
                <SelectTrigger>
                  <SelectValue placeholder='Select a client' />
                </SelectTrigger>
                <SelectContent>
                  {mockClients.map((c) => (
                    <SelectItem key={c.id} value={c.id}>
                      {c.fullName}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className='grid gap-3 sm:grid-cols-2'>
              <div className='space-y-1.5'>
                <Label>Date</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button
                      variant='outline'
                      className={cn(
                        'w-full justify-start text-left font-normal',
                        !formDate && 'text-muted-foreground'
                      )}
                    >
                      <CalendarIcon className='mr-2 h-4 w-4' />
                      {formDate ? format(formDate, 'PPP') : <span>Pick a date</span>}
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className='w-auto p-0' align='start'>
                    <Calendar
                      mode='single'
                      selected={formDate}
                      onSelect={(d) => d && setFormDate(d)}
                      initialFocus
                      className={cn('p-3 pointer-events-auto')}
                    />
                  </PopoverContent>
                </Popover>
              </div>
              <div className='space-y-1.5'>
                <Label>Price ($)</Label>
                <Input
                  type='number'
                  min={0}
                  placeholder='0'
                  value={formPrice}
                  onChange={(e) => setFormPrice(e.target.value)}
                />
              </div>
            </div>
            <div className='space-y-1.5'>
              <Label>Location</Label>
              <Input
                placeholder='Job location'
                value={formLocation}
                onChange={(e) => setFormLocation(e.target.value)}
              />
            </div>
            <div className='space-y-1.5'>
              <Label>Notes</Label>
              <Textarea
                placeholder='Additional notes...'
                value={formNotes}
                onChange={(e) => setFormNotes(e.target.value)}
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant='outline'
              onClick={() => {
                setCreateOpen(false);
                resetForm();
              }}
            >
              Cancel
            </Button>
            <Button onClick={handleCreate}>Create Job</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default Jobs;
